version: "3.8"
services:
    api:
        build: ./
        ports:
            - 80:9406
        networks:
            - app-network
        environment:
            NODE_ENV: production
            PORT: 9406
        command: npm run local
    nginx:
        build: ./nginx
        ports:
            - 80:80
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
